### ISSUE TITLE
2 - Add Tech and Tools Section after MVP but before board generation

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#10]
Verbiage: TBD

UI:
 - Ability to add and remove individual input fields
 - Ability to fill out those fields and submit.

Function:
- On submit, the board will build and these line items will populate as tasks under the "Tech and Tools" section of the board.

**Comment by lifeingray** [comment]
What technology will the team use to deliver this work?  What languages?  Libraries?  Repositories? Where will you host it?  What domain might it have?  Let's agree on our tools up front and list them here so we have a checklist of things to setup after we get started.

**Comment by jbunting** [comment]
This is functionally working - but needs some magic from @Cale.

**Comment by jbunting** [comment]
To clarify, I attempted to add breadcrumbs and update styles, but I'm not sure that I got all of them. In addition, I did not add any icons for that step.
