### ISSUE TITLE
3 - Add a informational modal to the gravity board 

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#12]
Needs:
When to board loads, we see a simple modal
Copy - TBD

Wants:
Prefer it to only come up once, on first visit
If we add the breadcrumbs to the Gravity Board, clicking on "Gravity" while on the gravity board would re-pop this modal

**Comment by Cale** [comment]
Probably kind of hacky on the JS side, but modal fires on page load.

I added a "?" link to the board instead of linking to "Gravity." The same link would appear on all pages the way the template is set up.

**Comment by lifeingray** [comment]
Copy:

Now that you've broken your MVP into workstreams, it's time to identify the necessary tasks needed to deliver each individual workstream.  Click on the "+" button at the top of each workstream column, and add the general tasks your team agrees need to take place to get that done.

Once you've identified the tasks, be sure to challenge each task on the board for its necessary towards your minified MVP.  If you don't have complete a task to deliver, then that task should come off the board now and not be done as part of your build.

I'm Ready >>

**Comment by lifeingray** [comment]
lgtm :+1:
