### ISSUE TITLE
Upgrade - Email should link to Gravity Board

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#24]
The team email links us to: http://www.pinch.tn/walkthrough/test1-anpfp3
Which resolves to: http://www.pinch.tn/walkthrough/test1-anpfp3/minify_mvp/
It should link and/or resolve to: http://www.pinch.tn/walkthrough/test1-anpfp3/gravity_board/

I don't think i'd mind much, but the 'new' team members won't know what to do here and even when they figure it out their actions (and even inactions) have consequences on the columns on the board.  I navigated to the board this way as a 'new' team member and it made a new blank column on the board.

**Comment by jbunting** [comment]
So, I think that resolving this requires some decisions. The link in the email doesn't necessarily resolve to "minify_mvp" -- it resolves to the point in the process that the project is currently at. If the mvp hasn't been minified, it'll go there. If everything's done, it'll go to the gravity board. 

I don't know how sending team member directly to the gravity board before the process is complete will work -- the app wasn't designed to allow that initially. 

Just tested it -- this is what it looks like: http://www.pinch.tn/walkthrough/jtest-kgpdje/gravity_board/

So, my recommendation is that we either leave it as is, or don't send the email until the gravity board step is reached. Another option is to have two emails -- one to send to the owner when it's first created, and another to send to all members (including the email) saying "The gravity board for your project is ready -- check it out here!" (or something to that effect)

Thoughts?

**Comment by lifeingray** [comment]
I'm not sure we documented it well enough, but when we discussed it we talked about delaying the email send until they landed on the gravity board (making this a potential non-issue).  If that part happens or not, the email should absolutely send them to the gravity board.

**Comment by jbunting** [comment]
Alright, my plan then is to delay the email until hitting the gravity board. The only downside I see is if the project creator loses the url before getting there, they won't be able to get back. But that seems like a pretty easy "don't do that" or "start again".
