### ISSUE TITLE
Low - Gravity Board can't really deal with long workstream names

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#27]
Problem: http://screencast.com/t/Ma1HAzoh
Board: http://www.pinch.tn/walkthrough/test-08hz7s/gravity_board/

I tried a few things with CSS to offer here without changing the markup, I didn't see anything offhand that was working.  There's a "quick fix" that can happen where we move the button to be after the h4 that makes it ok, it just messes up the position of the tickets a bit.

If you see a better way @Cale, go for it.

**Comment by Cale** [comment]
This is all patched up, @lifeingray
