### ISSUE TITLE
Moderate - App Asplodez when no email addy given

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#28]
Feel free to make email (and Project name) a required field. JS validation layer is fine, it's going to catch most everyone.  Whatever is easy to do.

=================

SMTPRecipientsRefused at /walkthrough/test-jq2elx/select_tools/
{'': (501, 'Syntax error')}
Request Method:    POST
Request URL:    http://www.pinch.tn/walkthrough/test-jq2elx/select_tools/
Django Version:    1.6.2
Exception Type:    SMTPRecipientsRefused
Exception Value:    
{'': (501, 'Syntax error')}
Exception Location:    /app/.heroku/python/lib/python2.7/smtplib.py in sendmail, line 735
Python Executable:    /app/.heroku/python/bin/python
Python Version:    2.7.6
Python Path:    
['/app/pinch',
'/app',
'/app/.heroku/python/bin',
'/app/.heroku/python/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg',
'/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg',
'/app',
'/app/.heroku/python/lib/python27.zip',
'/app/.heroku/python/lib/python2.7',
'/app/.heroku/python/lib/python2.7/plat-linux2',
'/app/.heroku/python/lib/python2.7/lib-tk',
'/app/.heroku/python/lib/python2.7/lib-old',
'/app/.heroku/python/lib/python2.7/lib-dynload',
'/app/.heroku/python/lib/python2.7/site-packages',
'/app/pinch',
'/app/pinch/pinch']

**Comment by jbunting** [comment]
This should be fixed, but it needs some css love from @Cale.

**Comment by lifeingray** [comment]
If you're feeling brave, add a class of "validate_tooltip" to them and then add this to the css file. It will look like this: http://screencast.com/t/x9rUU5m1va

`
.validate_tooltip {
  display: block;
  margin: 5px;
  padding: 5px;
  background: #FFCCCC;
  border-radius: 5px;
  border: 1px solid #ff6666;
  font-weight: bold;
}
`
