### ISSUE TITLE
1 - Collect more user data at project name screen

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#7]
Need:
- Project Name
- Event (Prefill: "Hack Tennessee")
- Your Name (required)
-  Your Email Address (required)

Want:
Multiples (all optional)
- Team Member Name 
- Team Member Email
( + and - controls to add team members)

@Cale feel free to add some labels to the project name screen for each field.
Project Name: ____
Event: _____
etc.

**Comment by jbunting** [comment]
Do we want the team member name and email to be entered on the same page as the "project name" or should we add another "collect details" page?

**Comment by jbunting** [comment]
In the same vein, my plan was to add this stuff to the pages and then let @Cale style it up. Does that sound good?

**Comment by jbunting** [comment]
This is ready for @Cale magic touch.

**Comment by Cale** [comment]
Added some style updates to master.

**Comment by lifeingray** [comment]
This looks done, if you all are happy with it!

**Comment by Cale** [comment]
:shipit:

**Comment by jbunting** [comment]
Closing per @lifeingray's comment -- @Cale feel free to reopen if you disagree
