### ISSUE TITLE
2 - Improve MVP steps

### ISSUE THREAD

**Issue by lifeingray** [pinch-tn/pinch-app#9]
Need more thought here.

**Comment by Cale** [comment]
@lifeingray I changed up the statements to look like they're no longer in a text box and also made the call to action larger, with an example strikethrough and highlight. 

That might be enough? Take a look and see what you think. I hope it makes the user pause and think a bit longer about what needs to be done. (Something other than writing.)

**Comment by lifeingray** [comment]
It's an improvement for sure, let's roll with this.  Thanks, Cale!
